//
//  strings.swift
//  Libbris
//
//  Created by 郝育宽 on 2021-09-01.
//

import Foundation
let strLanguageSetting = "Language Setting"
let strInfos = "Information"
let strConfig = "Configuration"
let strSkip = "Skip"
let strTeam = "Team"
let strMail = "mail"
let strVersion = "Version"
let strOnReading = "ON READING"
let strToRead = "TO READ"
let strEnglish = "English"
let strChinese = "Chinese(Simplified)"
let strFrench = "French"
let strBack = "<Back"
let apiWebsite = "http://libbris2021.us-west-2.elasticbeanstalk.com/ws/"
let apiGetBookByCategory = "\(apiWebsite)/book/category/\(1)?start=\(1)&size=\(1)"
let apiSearch = "\(apiWebsite)book/searchByName?name=\(1)"
let apiGetbook = "\(apiWebsite)book/\(1)"
let apiGetChapterContent = "\(apiWebsite)book/\(1)/chapter/\(1)"
let apiGetAllChapters = "\(apiWebsite)book/\(1)/chapters"
let apiFindCategoriesByLanguage = "\(apiWebsite)category/findByLanguage?lang=\("en")"
let apiAllGetFeaturedBookList = "\(apiWebsite)featured/all/\("long")"
let apiGetFeaturedBookList = "\(apiWebsite)featured/\("long")/\("long")"
let apiListAllLanguages = "\(apiWebsite)language/list"
let apiRankControllerSearch = "\(apiWebsite)rank/\("rankTypeName")/\("categoryId")/\("cycle")/\("size")"
let strRecommend = "RECOMMEND"
let strHot = "HOT"
let strNew = "NEW"
let strMore = "MORE"
let strLibrary = "LIBRARY"
let strSettings = "SETTINGS"
let strSearch = "Search"
let strNoMoreBook = "No more books"
let strSubmit = "Submit"
let strSearchArea = "search area"
let strApplicationSetting = "Application Setting"
let strPrivacyAndSafety = "Privacy & Safety"
let strOthers = "Other"
let strLoading = "Loading..."
let strChinese1 = "中文（简体）"
let strClearData = "clearData"
